// EDUEME ROBOTICS EXPO 2026 — CURRENT PROJECT DATA
// Add video URLs later in the `video` field for each project.
const projects = [
  {
    number: 1,
    title: 'Clap-Based Lamp',
    students: 'Samuel & Ashar',
    grade: 'Grade 5-B',
    controller: 'Arduino UNO',
    category: 'Automation',
    image: 'assets/images/Project-1(Clap Based Lamp).jpg',
    description: 'A hands-free lighting system that responds to a clap or another sharp sound. The project demonstrates how a sound sensor and Arduino can be combined to control a light without using a conventional switch.',
    problem: 'Turning a light on manually is not always convenient, especially when our hands are occupied or when the switch is not nearby.',
    solution: 'A sound sensor detects a clap and sends the signal to an Arduino UNO. The Arduino processes the signal and controls the connected light output.',
    working: ['The sound sensor continuously monitors the surrounding sound level.', 'A clap or sharp sound crosses the programmed detection threshold.', 'Arduino reads the sensor signal and identifies the sound event.', 'The programmed output switches the lamp or LED ON or OFF.', 'The system can be calibrated so normal background noise does not trigger it easily.'],
    components: ['Arduino UNO', 'Sound sensor / microphone module', 'LED or lamp output circuit', 'Buzzer (optional)', 'Resistors and jumper wires'],
    build: 'The students connected the sound sensor to an Arduino input, connected the light output through a suitable driver circuit, uploaded the control program and adjusted the sound threshold through testing.',
    applications: ['Hands-free lighting', 'Smart-home demonstrations', 'Accessibility-focused controls', 'Basic sound-based automation'],
    video: ''
  },
  {
    number: 2,
    title: 'Smart Toll Gate',
    students: 'Sathvik & Yuvaan',
    grade: 'Grade 5-Innovator',
    controller: 'Arduino UNO',
    category: 'Automation',
    image: 'assets/images/Project-2(Toll Gate).jpg',
    description: 'A miniature automated toll-gate model that demonstrates how sensors and a motorized barrier can be used to manage vehicle entry at a toll point.',
    problem: 'A conventional toll barrier requires manual operation and can take time to respond to every approaching vehicle.',
    solution: 'A sensor detects an approaching vehicle and Arduino controls a servo motor to raise and lower the barrier automatically.',
    working: ['A vehicle approaches the toll-gate model.', 'The sensor detects the vehicle and sends a signal to Arduino.', 'Arduino activates the servo motor.', 'The barrier rises to allow the vehicle to pass.', 'After the programmed delay, the barrier returns to the closed position.'],
    components: ['Arduino UNO', 'IR or distance sensor', 'Servo motor', 'Barrier arm', 'LED indicators', 'Jumper wires'],
    build: 'The students built a miniature toll lane, attached a lightweight barrier to a servo motor, positioned a detection sensor and programmed the Arduino to control the opening and closing sequence.',
    applications: ['Automated toll systems', 'Parking entrances', 'Access-control gates', 'Smart-city models'],
    video: ''
  },
  {
    number: 3,
    title: 'RFID Door Lock',
    students: 'Bhavya & Raheem',
    grade: 'Grade 5-S',
    controller: 'Arduino UNO',
    category: 'Security',
    image: 'assets/images/Project-3(Door Lock RFID).jpg',
    description: 'An electronic access-control system that uses RFID technology to identify an authorized card or tag before unlocking a model door.',
    problem: 'Physical keys can be lost or copied. Electronic identification can provide a more controlled way to demonstrate secure access.',
    solution: 'An RFID reader scans a card or tag. Arduino compares its ID with the authorized IDs stored in the program and activates the lock when a valid card is detected.',
    working: ['An RFID card or tag is placed near the reader.', 'The RFID module reads the tag ID.', 'Arduino compares the ID with the authorized list.', 'If the ID is valid, the lock actuator is activated.', 'If the ID is not recognized, access remains locked and an alert can be given.'],
    components: ['Arduino UNO', 'RFID reader module', 'RFID cards/tags', 'Servo or lock actuator', 'LED', 'Buzzer', 'Jumper wires'],
    build: 'The students connected the RFID reader to Arduino, programmed authorized tag IDs, connected the locking actuator and created a small door model for demonstration.',
    applications: ['Smart doors', 'School access systems', 'Cabinet locks', 'Basic electronic security demonstrations'],
    video: ''
  },
  {
    number: 4,
    title: 'Obstacle Avoidance Bot',
    students: 'Hridaan & Saketh',
    grade: 'Grade 5-C',
    controller: 'Arduino UNO',
    category: 'Robotics',
    image: 'assets/images/Project-4(obstacle Bot).jpg',
    description: 'A mobile robot that detects obstacles in its path and changes direction to avoid collisions. It demonstrates the basic principles of autonomous navigation.',
    problem: 'A moving robot needs to understand what is in front of it if it is expected to navigate without continuously hitting objects.',
    solution: 'A distance sensor measures the space ahead. Arduino uses that measurement to stop, turn and continue moving when an obstacle is detected.',
    working: ['The robot moves forward using its drive motors.', 'The distance sensor continuously checks the path.', 'When an obstacle is detected within the set distance, Arduino stops the motors.', 'The controller commands the motors to turn.', 'The robot checks the path again and resumes forward movement when it is clear.'],
    components: ['Arduino UNO', 'Ultrasonic/distance sensor', 'Motor driver', 'DC geared motors', 'Robot chassis', 'Wheels', 'Battery'],
    build: 'The students assembled the chassis and motors, mounted the distance sensor at the front, connected the motor driver and Arduino, then programmed distance-based movement decisions.',
    applications: ['Autonomous robots', 'Obstacle detection', 'Educational robotics', 'Indoor navigation prototypes'],
    video: ''
  },
  {
    number: 5,
    title: 'Flame Bot',
    students: 'Bhavyan & Viraj',
    grade: 'Grade 5-Pioneer',
    controller: 'Arduino UNO',
    category: 'Robotics',
    image: 'assets/images/Project-5(Flame Bot).jpg',
    description: 'A fire-detection robot concept that uses a flame sensor to identify the direction of a flame and move toward the detected source.',
    problem: 'Locating a flame quickly can be difficult and approaching a fire can be unsafe. A robotic detection concept can demonstrate how sensing and movement may be combined.',
    solution: 'The flame sensor detects infrared radiation associated with a flame. Arduino interprets the sensor signal and controls the robot motors based on the detected direction.',
    working: ['The flame sensor monitors for a flame source.', 'Arduino reads the sensor output.', 'The controller determines the direction of the detected flame.', 'The motor driver moves the robot toward the detected direction.', 'The system can be extended with an alarm or extinguishing mechanism.'],
    components: ['Arduino UNO', 'Flame sensor', 'Motor driver', 'DC motors', 'Robot chassis', 'Battery', 'Buzzer/LED'],
    build: 'The students mounted the flame sensor on the robot, assembled the motor system, connected the driver and Arduino, calibrated the sensor and programmed directional movement.',
    applications: ['Fire-detection demonstrations', 'Search-and-detection robotics', 'Safety technology prototypes', 'Robotics learning'],
    video: ''
  },
  {
    number: 6,
    title: 'Automatic Plant Watering',
    students: 'Vihaan & Shankir',
    grade: 'Grade 4-S',
    controller: 'Arduino UNO',
    category: 'Environment',
    image: 'assets/images/Project-7(Plant Watering System).jpg',
    description: 'An automatic plant-watering system that monitors soil moisture and supplies water when the soil becomes too dry.',
    problem: 'Plants may be under-watered when people forget to water them, while unnecessary watering can waste water.',
    solution: 'A soil-moisture sensor measures the condition of the soil and Arduino activates a small pump when the moisture level falls below a chosen threshold.',
    working: ['The moisture sensor measures the soil condition.', 'Arduino reads the sensor value.', 'The value is compared with the programmed moisture threshold.', 'If the soil is dry, the pump is switched ON.', 'When sufficient moisture is reached, the pump is switched OFF.'],
    components: ['Arduino UNO', 'Soil moisture sensor', 'Mini water pump', 'Relay/MOSFET driver', 'Water tube', 'Plant pot', 'Power supply'],
    build: 'The students placed the moisture sensor in soil, connected a small pump through a suitable driver, programmed the moisture threshold and tested automatic watering with different soil conditions.',
    applications: ['Home gardening', 'Smart agriculture', 'Water conservation', 'Plant-care automation'],
    video: ''
  },
  {
    number: 7,
    title: 'Water Level Monitor',
    students: 'Ridhan & Hannan',
    grade: 'Grade 4-A',
    controller: 'Arduino UNO',
    category: 'Environment',
    image: 'assets/images/Project-8(Water level).jpg',
    description: 'A water-level monitoring model that detects the amount of water in a tank and provides visual or audio alerts when the level changes.',
    problem: 'Overflowing tanks can waste water, while unexpectedly low water levels can interrupt supply.',
    solution: 'A water-level or distance sensor measures the tank condition and Arduino uses the reading to indicate low, medium and high water levels.',
    working: ['The sensor measures the water level.', 'Arduino receives and interprets the sensor reading.', 'The reading is compared with programmed level ranges.', 'LEDs or a buzzer indicate the current water condition.', 'The project can be extended to control a pump automatically.'],
    components: ['Arduino UNO', 'Water-level or ultrasonic sensor', 'LEDs', 'Buzzer', 'Resistors', 'Jumper wires'],
    build: 'The students created a tank model, positioned the sensor, connected LEDs and a buzzer, then programmed different thresholds for the water levels.',
    applications: ['Overhead tank monitoring', 'Water conservation', 'Smart-home models', 'Industrial level-monitoring concepts'],
    video: ''
  },
  {
    number: 8,
    title: 'Temperature Monitoring System',
    students: 'Naithik & Kundana',
    grade: 'Grade 5-Stal',
    controller: 'Arduino UNO',
    category: 'Monitoring',
    image: 'assets/images/Project-9(Tmeperatrue Monitoring System).jpg',
    description: 'A temperature-monitoring project that measures the surrounding temperature and presents the reading to the user. It introduces students to sensors, measurement and data interpretation.',
    problem: 'Temperature can change throughout the day and may need to be measured to understand or monitor an environment.',
    solution: 'A temperature sensor sends a measurement to Arduino, which processes the reading and communicates it through a display, serial output or indicator.',
    working: ['The temperature sensor measures the surrounding environment.', 'Arduino reads the sensor signal.', 'The sensor value is converted into a temperature reading.', 'The reading is displayed or used to trigger an alert when a threshold is reached.'],
    components: ['Arduino UNO', 'Temperature sensor', 'Display or serial monitor', 'LED/buzzer (optional)', 'Jumper wires'],
    build: 'The students connected the temperature sensor to Arduino, programmed the sensor-reading logic, tested the values against the environment and added an output method for displaying the result.',
    applications: ['Room monitoring', 'Weather and environmental projects', 'Smart-home systems', 'Temperature-alert systems'],
    video: ''
  },
  {
    number: 9,
    title: 'Anti-Theft Alarm',
    students: 'Vishisht & Sushmith',
    grade: 'Grade 4-Explorer',
    controller: 'Arduino UNO',
    category: 'Security',
    image: 'assets/images/Anti-theft Alarm.jpg',
    description: 'A security-alert project that detects an unexpected movement, opening or intrusion and activates an alarm to warn the user.',
    problem: 'Homes, rooms and valuable objects may need a simple alert when an unauthorized person tries to enter or disturb them.',
    solution: 'A sensor detects a suspicious event and Arduino activates a buzzer or other indicator to create an immediate warning.',
    working: ['The system remains in monitoring mode.', 'A sensor watches for the selected intrusion condition.', 'When the condition is detected, Arduino changes to alarm mode.', 'The buzzer and/or warning LED is activated.', 'The alarm can be reset after the situation is checked.'],
    components: ['Arduino UNO', 'Motion, IR or magnetic sensor', 'Buzzer', 'LED', 'Resistors', 'Jumper wires', 'Battery/power supply'],
    build: 'The students selected a sensor for the intrusion condition, connected it to Arduino, added an alarm output and programmed the system to respond when the sensor state changes.',
    applications: ['Door security', 'Cabinet protection', 'Room intrusion alerts', 'Basic security systems'],
    video: ''
  },
  {
    number: 10,
    title: 'Rain Protection System',
    students: 'Kian & Medhansh',
    grade: 'Grade 4-C',
    controller: 'Arduino UNO',
    category: 'Automation',
    image: 'assets/images/Rain Protection System.jpg',
    description: 'An automatic rain-protection model that detects rainfall and responds by moving or activating a protective mechanism.',
    problem: 'Rain can damage clothes, books, electronic items and other objects that are left outdoors or near an open area.',
    solution: 'A rain sensor detects water droplets and Arduino activates a motorized or alert mechanism to protect the object.',
    working: ['The rain sensor continuously checks for water droplets.', 'When rain is detected, the sensor signal changes.', 'Arduino processes the signal.', 'A motor/servo or alert is activated to move the protective cover or warn the user.', 'When the rain condition ends, the system can return to standby.'],
    components: ['Arduino UNO', 'Rain sensor module', 'Servo/DC motor', 'Motor driver if required', 'LED/buzzer', 'Protective cover mechanism'],
    build: 'The students created a small protective mechanism, positioned the rain sensor, connected the actuator to Arduino and programmed the system to respond when water is detected.',
    applications: ['Automatic clothes-cover systems', 'Smart windows', 'Outdoor equipment protection', 'Weather-responsive automation'],
    video: ''
  },

  {
    number: 11,
    title: 'Smart Parking System',
    students: 'Sanjana, Ishaa & Chaitra',
    grade: 'Grade 5-Explorer / Thinker',
    controller: 'Arduino UNO',
    category: 'Smart Systems',
    image: 'assets/images/smart parking system.jpg',
    description: 'A smart parking model that demonstrates how sensors can detect vehicle presence and help indicate whether parking spaces are occupied or available.',
    problem: 'In busy parking areas, drivers can spend time searching for an empty space. A simple automated indication system can make parking easier to understand and manage.',
    solution: 'The model uses sensors to detect whether a parking slot is occupied. Arduino processes the sensor readings and provides an indication of the parking status.',
    working: ['Sensors monitor the individual parking spaces.', 'When a vehicle enters a space, the sensor detects its presence.', 'Arduino reads the sensor signals and determines the occupancy status.', 'The system updates the corresponding indicator for each parking space.', 'The model can be expanded to show the number of available spaces at the entrance.'],
    components: ['Arduino UNO', 'IR or distance sensors', 'LED indicators', 'Resistors', 'Breadboard and jumper wires', 'Miniature parking layout'],
    build: 'The students created a miniature parking layout, positioned sensors at the parking spaces, connected the indicators to Arduino and programmed the controller to respond to vehicle presence.',
    applications: ['Smart parking facilities', 'Parking guidance systems', 'Smart-city demonstrations', 'Vehicle management systems'],
    future: 'The system could be expanded with an entrance display, available-space counting, RFID-based access, mobile notifications and automated parking guidance.',
    tagline: 'Find a space faster. Park smarter.'
  },
  {
    number: 12,
    title: 'Smart Night Lamp',
    students: 'Nimai & Abdul',
    grade: 'Grade 4-T',
    controller: 'Arduino UNO',
    category: 'Smart Lighting',
    image: 'assets/images/automatic nyt lamp.jpg',
    description: 'An automatic lighting system designed to switch a lamp on when the surrounding environment becomes dark and reduce the need for manual switching.',
    problem: 'Night lights are often switched manually even though the need for light can be detected automatically from the surrounding brightness.',
    solution: 'A light sensor detects the brightness of the environment and Arduino uses the sensor reading to control the lamp according to a programmed threshold.',
    working: ['The light sensor continuously measures the surrounding brightness.', 'Arduino reads the sensor value.', 'The controller compares the reading with a programmed light threshold.', 'When the environment becomes dark, the lamp is switched ON.', 'When sufficient light returns, the lamp can be switched OFF automatically.'],
    components: ['Arduino UNO', 'LDR/light sensor', 'LED or lamp', 'Resistor', 'Breadboard', 'Jumper wires', 'Power supply'],
    build: 'The students connected the light sensor to an Arduino input, connected the lamp output, programmed a brightness threshold and tested the system under different lighting conditions.',
    applications: ['Automatic night lights', 'Home automation', 'Corridor lighting', 'Energy-saving lighting demonstrations'],
    future: 'The lamp could be improved with adjustable brightness, motion sensing, multiple lighting modes, rechargeable power and smart-home connectivity.',
    tagline: 'When darkness arrives, intelligence turns on.'
  }

];

// Exhibition storytelling layer
const expoEnhancements={
1:{why:'The project shows how a simple sound event can become a useful control signal. It introduces students to the idea of hands-free interaction and threshold-based sensing.',future:'The lamp could be extended with double-clap switching, adjustable sensitivity, a rechargeable power source and multiple appliance controls.',tagline:'One clap. Smart light. Smarter living.'},
2:{why:'The model demonstrates how a small sensor-controlled mechanism can automate a familiar road system and reduce the need for manual operation.',future:'Future versions could combine RFID or automatic vehicle identification, payment simulation, traffic lights and vehicle counting.',tagline:'A smarter gate for a smarter journey.'},
3:{why:'The project introduces digital identity: instead of depending only on a physical key, the system checks whether a particular RFID tag is authorized.',future:'It could be extended with multiple user IDs, access logs, a keypad backup, mobile authentication and stronger locking hardware.',tagline:'Your identity becomes the key.'},
4:{why:'The bot demonstrates the foundation of autonomous navigation: sense the environment, make a decision and move accordingly.',future:'The next version could use multiple sensors, smarter path selection, mapping and more advanced navigation algorithms.',tagline:'Sense. Decide. Move. Explore.'},
5:{why:'The project connects sensing with robotics to explore how machines can detect a potentially dangerous source and respond without direct human approach.',future:'It could be developed with directional sensing, remote monitoring, an alert system and a safe fire-extinguishing mechanism.',tagline:'Detect danger. Respond with intelligence.'},
6:{why:'The system connects plant care with automation by allowing the plant itself to influence when watering happens.',future:'A future version could add weather awareness, water-tank monitoring, multiple plant zones and mobile notifications.',tagline:'Let technology care for every drop and every leaf.'},
7:{why:'Water is a valuable resource, and this model makes an invisible quantity visible through sensing and alerts.',future:'The system could automatically control a pump, send overflow notifications and support multiple tanks or larger storage systems.',tagline:'Know the level. Save the water.'},
8:{why:'Temperature is an everyday measurement with applications from comfort to safety. This project turns a sensor reading into information people can understand.',future:'It could add data logging, threshold alarms, wireless monitoring and a live temperature dashboard.',tagline:'Measure the heat. Understand the environment.'},
9:{why:'The project explores how sensors and alerts can create a first layer of protection when unexpected activity is detected.',future:'It could include multiple sensors, keypad/RFID disarming, remote notifications and event logging.',tagline:'Detect the unexpected. Protect what matters.'},
10:{why:'The model demonstrates a practical response to changing weather conditions by using sensing and movement to protect an object or space.',future:'It could be extended with rain-intensity sensing, automatic closing logic, wind detection and remote alerts.',tagline:'When the weather changes, technology responds.'}
};
projects.forEach(p=>Object.assign(p,expoEnhancements[p.number]||{}));
